config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resources :friends

  get "/about", to: "pages#about_us"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  CATEGORIES = ["Beauty", "Eletronics", "Home & Garden", "Sports", "Watches"]
  belongs_to :user
  has_one_attached :avatar
end

app/models/gift.rb
class Gift < ApplicationRecord
  ProductCategory::CATEGORIES
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  CATEGORIES = ["Beauty", "Eletronics", "Home & Garden", "Sports", "Watches"]
  belongs_to :friend
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # after_create :send_welcome_email

  has_many :friend

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar

  private

  # def send_welcome_email
  #   UserMailer.with(user: self).welcome.deliver_now
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :avatar])
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends = Friend.where(user_id: current_user.id)
  end

  def new
    @friend = Friend.new
  end

  def create
    @friend = Friend.new(friends_params)
    @friend.user = current_user
    days_until_birthday @friend.birthday
    # UserMailer.welcome(current_user, @friend.product_category, @friend.id).deliver_now

    if @friend.save
      # UserMailer.welcome(current_user, @friend.product_category, @friend.id).deliver_now

      if days_until_birthday(@friend.birthday) == 7
        UserMailer.welcome(current_user, @friend.product_category, @friend.id).deliver_now
      end
      redirect_to '/friends'
    end
  end

  def destroy
    @friend = Friend.find(params[:id])
    @friend.destroy

    redirect_to friends_path
  end

  def edit
    @friend = Friend.find(params[:id])
    @friend_category = @friend.product_category
  end

  def update
    @friend = Friend.find(params[:id])
    @friend.update(friends_params)
      redirect_to '/friends'
  end

  private

  def friends_params
    params.require(:friend).permit(:name, :max_price, :birthday, :avatar, :product_category)
  end

  def days_until_birthday(birthday)
    bday = Date.new(Date.today.year, birthday.month, birthday.day)
    bday += 1.year if Date.today >= bday
    (bday - Date.today).to_i
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :about_us ]

  def home
  end

  def about_us
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/friends/edit.html.erb
<div class="container-edit">
  <section>
    <div>
      <h2 class="title-edit text-center my-4"> Edit Friend Info</h2>

      <div class="section-divider-edit container">
        <div class="space"></div>
        <div class="card">
          <div class="imgbox">
            <% if @friend.avatar.attached? %>
              <%= cl_image_tag @friend.avatar.key, class:"avatar-edit" %>
            <% else %>
              <%=image_tag('user.png')%>
            <% end %>
          </div>
        </div>

        <div>
          <%= simple_form_for @friend, html: { class: 'label-new-edit glass-edit p-4 mx-5' } do |f|  %>
            <%= f.input :name, input_html: { class: 'glass-label-edit'}, label: "Birthday Person" %>
            <%= f.input :max_price, as: :decimal, input_html: { class: 'glass-label-edit '}, label: "Max Gift Price(R$)" %>
            <%= f.input :birthday, :as => :date, :start_year => Date.today.year - 90,
                                :end_year => Date.today.year,
                                :order => [:day, :month, :year],
                                input_html: { class: 'glass-label-edit'} %>
            <%= f.input :product_category,collection: Friend::CATEGORIES, input_html: { class: 'glass-label-edit'}, label: 'Birthday Person Preference'  %>
            <div class="buttons-edit">
              <%= f.input :avatar, as: :file, input_html: { class: ' d-none', id: 'photo-input' },
              label_html:  { class: ' mt-4 cursor '}, label: '📷 Change Avatar' %>
              <%= f.button :submit, '👩🏾‍🤝‍👨🏻 Add Changes', class: "create-friend-edit" %>
            </div>
          <% end %>
        </div>
        <%# <%= image_tag "", width: 300, height: 300,class: "hidden", id: "photo-preview" %> %>

      </div>
    </div>
  </section>
</div>

app/views/friends/index.html.erb
<section id="team">
  <h2 class="title-index text-center my-5">Birthday List</h2>
  <div class="containerCards">
    <% @friends.each do |friend| %>
      <div class="containerCard">
        <div class="card">
            <% if friend.avatar.attached? %>
              <%= cl_image_tag friend.avatar.key, class:"img-fluid rounded-circle", alt:"Card image cap", crop: :fill %>
            <% else %>
              <%=image_tag('user.png', class:"rounded-circle")%>
            <% end %>
            <h3><%= friend.name.capitalize%></h3>
            <h5><span class="friends-detail"> Age: </span><%=((Time.zone.now - friend.birthday .to_time) / 1.year.seconds).floor%> years</h5>
            <h5><span class="friends-detail">Birthday: </span><%=friend.birthday.strftime("%B %d, %Y")%></h5>
            <h5><span class="friends-detail">Max Gift Price: </span><%=friend.max_price%> $</h5>
            <div class="icon">
              <%= link_to edit_friend_path(friend),
                class:"text-end btn-x flex-grow-1 icon mx-2" do %>
                <i class="fas fa-edit"></i>
              <% end %>
              <%= link_to friend_path(friend),
                method: :delete,
                data: { confirm: "Are you sure you want to delete '#{friend.name.capitalize}'?" },
                class:"text-end btn-x flex-grow-1 icon" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/friends/new.html.erb
<div class="effect-class container-new">
  <section>
    <div>
      <h2 class="title-new text-center my-4"> Add a Special Date</h2>
      <p class="new-text">To make someone become <strong> unforgettable </strong> to you,
          all you have to do is to fill the form below.
        Then it is up to us! <br> We'll send you an email one week
        before the date, presenting the most special gifts the
        birthday person will ever receive!
      </p>
      <div class="section-divider">
        <div class="wrapper">
            <div class="gallery">
              <ul>
                <li><img src="<%= image_path("family1.jpg")%>"></li>
                <li><img src="<%= image_path("family2.jpg")%>">></li>
                <li><img src="<%= image_path("family10.jpg")%>">></li>
                <li><img src="<%= image_path("family4.jpg")%>">></li>
                <li><img src="<%= image_path("family5.jpg")%>">></li>
                <li><img src="<%= image_path("family6.jpg")%>">></li>
                <li><img src="<%= image_path("family7.jpg")%>">></li>
                <li><img src="<%= image_path("family8.jpg")%>">></li>
                <li><img src="<%= image_path("family9.jpg")%>">></li>
              </ul>
            </div>
        </div>

        <div>
          <%= simple_form_for @friend, html: { class: 'label-new glass p-4 mx-5' } do |f|  %>
            <%= f.input :name, input_html: { class: 'glass-label'}, label: "Birthday Person" %>
            <%= f.input :max_price, as: :decimal, input_html: { class: 'glass-label'}, label: "Max Gift Price(R$)" %>
            <%= f.input :birthday, :as => :date, :start_year => Date.today.year - 90,
                                :end_year => Date.today.year,
                                :order => [:day, :month, :year],
                                input_html: { class: 'glass-label'} %>
            <%= f.input :product_category, collection: Friend::CATEGORIES, input_html: { class: 'glass-label'}, label: 'Birthday Person Preference'  %>
            <div class="buttons-new">
              <%= f.input :avatar, as: :file, input_html: { class: ' d-none' },
              label_html:  { class: ' mt-4 cursor '}, label: '📷 Upload Image' %>
              <%= f.button :submit, '👩🏾‍🤝‍👨🏻 Create a Friend', class: "create-friend" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="height: 100vh">
  <head>
    <title>YouReUnforgettable</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script>document.documentElement.className="js";var supportsCssVars=function(){var e,t=document.createElement("style");return t.innerHTML="root: { --tmp-var: bold; }",document.head.appendChild(t),e=!!(window.CSS&&window.CSS.supports&&window.CSS.supports("font-weight","var(--tmp-var)")),t.parentNode.removeChild(t),e};supportsCssVars()||alert("Please view this demo in a modern browser that supports CSS Variables.");</script>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/about_us.html.erb
		<section id="partners">
			<div class="container my-3 py-5 text-center">
				<div class="row mb-5">
					<div class="col">
						<h1>ABOUT US</h1>
						<h5 class="mt-3">If you are that person that lost too many friends because you forgot their birthdays, WE ARE HERE TO HELP! We want to make sure that never happens again</h5>
					</div>
				</div>

				<div class="row">
					<div class="col-lg-3 col-md-6">
						<div class="card">
							<div class="card-body">
								<img src="<%= image_path("leonardo.png")%>" class="img-fluid rounded-circle">
								<h3>Leonardo Fukuje</h3>
								<h5>Fullstack Developer</h5>
								<p>Sou tecnólogo em processos de produção formado pela Faculdade de tecnologia de São Paulo, atualmente trabalho no setor comercial da TROX Brasil. Adoro aprender coisas novas como diferentes tecnologias, línguas e etc.</p>
								<div class="d-flex flex-row justify-content-center">
									<div class="p-4">
										<a href="#">
											<i class="fab fa-instagram list"></i>
										</a>
									</div>
									<div class="p-4">
										<a href="#">
										<i  class="fab fa-linkedin list"></i>
										</a>
									</div>
									<div class="p-4">
										<a href="#">
											<i class="fab fa-github list"></i>
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="col-lg-3 col-md-6">
						<div class="card">
							<div class="card-body">
								<img src="<%= image_path("lorenzo.jpg")%>" class="img-fluid rounded-circle">
								<h3>Lorenzo Zuccarelli</h3>
								<h5>FullStack Developer</h5>
								<p>Estudante Avenues São Paulo. Tenho interesse em design, queria muito trabalhar algo que junta minha paixão por design com meu interesse em programação.</p>
								<div class="d-flex flex-row justify-content-center">
									<div class="p-4">
										<a href="https://instagram.com/lorenzo.zuccarelli?igshid=ZDYzZTNjNWY=">
											<i class="fab fa-instagram list"></i>
										</a>
									</div>
									<div class="p-4">
										<a href="www.linkedin.com/in/lorenzo-zuccarelli-74614524a">
											<i class="fab fa-linkedin list"></i>
										</a>
									</div>
									<div class="p-4">
										<a href="https://github.com/lorenpzucca">
											<i class="fab fa-github list"></i>
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="col-lg-3 col-md-6">
						<div class="card">
							<div class="card-body">
								<img src="<%= image_path("mateus.jpg")%>" class="img-fluid rounded-circle">
								<h3>Mateus Ferreira</h3>
								<h5>FullStack Developer</h5>
								<p>I'm graduated in software engineer, love to solve problems and learning new ways to do a task. After Le Wagon I intend to get a job in exterior.</p>
								<div class="d-flex flex-row justify-content-center">
									<div class="p-4">
										<a href="#">
											<i class="fab fa-instagram list"></i>
										</a>
									</div>
									<div class="p-4">
										<a href="#">
											<i class="fab fa-linkedin list"></i>
										</a>
									</div>
									<div class="p-4">
										<a href="#">
											<i class="fab fa-github list"></i>
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>

					<div class="col-lg-3 col-md-6">
						<div class="card">
							<div class="card-body">
								<img src="<%= image_path("murilo.jpg")%>" class="img-fluid rounded-circle">
								<h3>Murilo Bergamin</h3>
								<h5>FullStack Developer</h5>
								<p>Olá, meu nome é Murilo Henrique Bergamin, sou de Jaú, interior do estado de São Paulo, atualmente auxiliar administrativo, formado em Tecnologia da Informação pela Fatec de Jaú, estou em busca de novos ares, inclusive uma nova carreira.</p>
								<div class="d-flex flex-row justify-content-center">
									<div class="p-4">
										<a href="#">
											<i class="fab fa-instagram list"></i>
										</a>
									</div>
									<div class="p-4">
										<a href="#">
											<i class="fab fa-linkedin list"></i>
										</a>
									</div>
									<div class="p-4">
										<a href="#">
											<i class="fab fa-github list"></i>
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>

app/views/pages/home.html.erb
<section class="home-section">
  <h1><span class="home-detail"> You're</span></h1>
  <h1 class="mb-5"> Unforgettable!</h1>
  <div class="set">
    <div><img class="family" src="<%= image_path("family1.jpg")%>"></div>
    <div><img class="family" src="<%= image_path("family2.jpg")%>"></div>
    <div><img class="family" src="<%= image_path("family3.jpg")%>"></div>
    <div><img class="family" src="<%= image_path("family4.jpg")%>"></div>
  </div>
  <div class="set set2">
    <div><img class="family" src="<%= image_path("family5.jpg")%>"></div>
    <div><img class="family" src="<%= image_path("family6.jpg")%>"></div>
    <div><img class="family" src="<%= image_path("family7.jpg")%>"></div>
    <div><img class="family" src="<%= image_path("family8.jpg")%>"></div>
  </div>
  <div class="set set3">
    <div><img class="family" src="<%= image_path("family9.jpg")%>"></div>
    <div><img class="family" src="<%= image_path("family10.jpg")%>"></div>
    <div><img class="family" src="<%= image_path("family1.jpg")%>"></div>
     <div><img class="family" src="<%= image_path("family8.jpg")%>"></div>
  </div>
</section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
      <span class="typed-fixed">A simple gift  </span><span class="typed-shift" data-controller="typed-js"></span>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home Page", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Birthday", "/friends/new", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Birthday List", "/friends/", class: "nav-link" %>
        </li>
        <li class="dropdown">
        <% if current_user.avatar.attached? %>
          <%= cl_image_tag current_user.avatar.key, style: "height: 40px; width: 40px; object-fit: cover;",class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%=image_tag('user.png', style: "height: 40px; width: 40px; object-fit: cover;",class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false)%>
        <% end %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown" style="rigth: 0">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "About us", "/about", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>